os:
  - linux
language: php
dist: trusty

php:
  - '7.1'
services:
  - docker
jobs:
  include:
    - stage: "Tests"
      name: "Unit Text PHP"
      script:
      - travis_retry composer self-update
      - travis_retry composer install --prefer-sources --no-interaction
      - cp .env.example .env
      - php artisan key:generate
      - vendor/bin/phpunit tests/Feature/ExampleTest.php

      - stage: "Build Docker Image"
        name: "Build Images Docker"
        script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t travis-ci-build-stages-demo .
        - docker images
        - docker tag travis-ci-build-stages-demo $DOCKER_USERNAME/latihan-cicd-laravel
        - docker push $DOCKER_USERNAME/latihan-cicd-laravel